version: "3.8"

services:
    superset:
        image: apache/superset:latest
        container_name: superset
        ports:
            - "8088:8088"
        environment:
            - SUPERSET_SECRET_KEY=your_secret_key_here
            - SUPERSET_LOAD_EXAMPLES=no
        volumes:
            - superset-data:/app/superset_home
        networks:
            - iot-network
        command: >
            bash -c "
            superset db upgrade &&
            superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
            superset init &&
            superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
            "
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 60s

volumes:
    superset-data:

networks:
    iot-network:
        external: true
